apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: host.docker.internal:5432  
    user: eurobae
    secureJsonData:
      password: eurobea0309
    jsonData:
      sslmode: "disable"  
      database: ZAP_DB
      postgresVersion: 1400
      timescaledb: false
    readOnly: false
