apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: sweng36.postgres.database.azure.com:5432  # This is the IP address of the PostgreSQL
    user: eurobae
    secureJsonData:
      password: Dkfvksmreo12!
    jsonData:
      sslmode: "require"
      database: ZAP_DB
      postgresVersion: 1400
      timescaledb: false
    readOnly: false
