apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: host.docker.internal:5432
    user: yar
    secureJsonData:
      password: 123
    jsonData:
      sslmode: "disable"
      database: DB_ZAP
      postgresVersion: 1400
      timescaledb: false
    readOnly: false
