apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: localhost:5432
    user: postgres
    secureJsonData:
      password: awsrdsPassword1234
    jsonData:
      sslmode: "disable"
      database: zap_db 
      postgresVersion: 1400
      timescaledb: false
    readOnly: false