apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: host.docker.internal:5432  
    database: ZAP_DB
    user: grafana_user
    secureJsonData:
      password: eurobea0309
    jsonData:
      sslmode: "disable"  
      postgresVersion: 1200
      timescaledb: false
