apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: 172.20.10.12:5432  # This is the IP address of the PostgreSQL 
    user: postgres
    secureJsonData:
      password: awsrdsPassword1234
    jsonData:
      sslmode: "disable"
      database: zap_db
      postgresVersion: 1400
      timescaledb: false
    readOnly: false