stages:
  - run_pen_test

# TODO
# Include this stage as an external resource into the gitlab-ci.yml

run_pen_test:
  stage: run_pen_test
  tags:
    - tudor-mac
  image: owasp/zap2docker-stable
  script:
    # Run your command and capture its output.
    - mkdir -p data
    - START_TIME=$(date +%s)
    - /System/Volumes/Data/Applications/ZAP.app/Contents/Java/zap.sh -cmd -script "$CI_PROJECT_DIR/zest-scrips/sql_injection_fail.zst" > data/output.txt
    - /System/Volumes/Data/Applications/ZAP.app/Contents/Java/zap.sh -cmd -script "$CI_PROJECT_DIR/zest-scrips/premium_key_get.zst" >> data/output.txt
    - /System/Volumes/Data/Applications/ZAP.app/Contents/Java/zap.sh -cmd -script "$CI_PROJECT_DIR/zest-scrips/sql_injection_login_2.zst" >> data/output.txt
    - END_TIME=$(date +%s)
    - 'echo "Time taken: $((END_TIME - START_TIME)) seconds" >> $CI_PROJECT_DIR/data/output.txt'
    - 'echo "Test Suite: Zest Security Tests" >> $CI_PROJECT_DIR/data/output.txt'
    - 'echo "Test Type: advanced" >> $CI_PROJECT_DIR/data/output.txt'
    - 'echo "Category: general" >> $CI_PROJECT_DIR/data/output.txt'
    - python3 py-scripts/json_processing.py $CI_PROJECT_DIR/data/output.txt $CI_PROJECT_DIR/data/output.json $CI_PROJECT_DIR/data/metadata.json
  # Artifacts are saved even if the job fails:
  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/SecOps/artifacts/output.txt
      - $CI_PROJECT_DIR/SecOps/artifacts/output.json
