
stages:
  - start_services
  - save_results
  - visualize

# 1️⃣ Juice Shop execute
start_juice_shop:
  image: docker:latest
  stage: start_services
  services:
    - docker:dind
  tags:
    # - euro-mac
    - yaroslav-mac
  script:
    - echo "Checking if Juice Shop is already running..."
    - docker ps -a | grep "juice-shop" && docker rm -f juice-shop || echo "No existing container."
    - echo "Starting Juice Shop..."
    - docker run -d --name juice-shop -p 3000:3000 bkimminich/juice-shop
    - sleep 10
    - docker ps


# 3️⃣ save JSON data to PostgreSQL
save_to_db:
  image: python:3.9
  stage: save_results
  needs:
    - run_pen_test
  before_script:
    - pip3 install psycopg2-binary
  tags:
    # - euro-mac
    - yaroslav-mac
  script:
    - python3 ZAP/Main/send_test_results_to_SQL.py
  allow_failure: false

# 4️⃣ Grafana
grafana_visualization:
  stage: visualize
  tags:
    - euro-mac
  script:
    - echo "Stopping any existing Grafana container..."
    - docker stop grafana || true
    - docker rm grafana || true

    - echo "Starting Grafana with PostgreSQL as its database and provisioning settings..."
    - docker run -d --name=grafana 
        -p 4000:3000 
        -v grafana_data:/var/lib/grafana 
        -v $CI_PROJECT_DIR/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards 
        -v $CI_PROJECT_DIR/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources 
        -v $CI_PROJECT_DIR/grafana/dashboards:/var/lib/grafana/dashboards
        grafana/grafana:latest

    - sleep 20  

    - echo "Checking Grafana logs..."
    - docker logs grafana

    - echo "Testing Grafana provisioning..."
    - curl -s -u admin:admin http://localhost:4000/api/search?query=



